import {NavigationContainer} from '@react-navigation/native';
import {createNativeStackNavigator} from '@react-navigation/native-stack';
import {StatusBar} from 'expo-status-bar';

import LoginScreen from './screens/LoginScreen';
import SignupScreen from './screens/SignupScreen';
import WelcomeScreen from './screens/WelcomeScreen';
import {Colors} from './constants/styles';
import AuthContextProvider, {AuthContext} from "./store/auth-context";
import {useContext} from "react";
import IconButton from "./components/ui/IconButton";

const Stack = createNativeStackNavigator();

/**
 *  At the moment we're using the token to find out whether a user is authenticated or not. That's one of the main use case but token plays another role
 *      - The token is generated by our Firebase project & we can also use this token to get access to the protected resources on our backend.
 *      - Refer WelcomeScreen.js
 */
function AuthStack() {
    return (
        <Stack.Navigator
            screenOptions={{
                headerStyle: {backgroundColor: Colors.primary500},
                headerTintColor: 'white',
                contentStyle: {backgroundColor: Colors.primary100},
            }}
        >
            <Stack.Screen name="Login" component={LoginScreen}/>
            <Stack.Screen name="Signup" component={SignupScreen}/>
        </Stack.Navigator>
    );
}

function AuthenticatedStack() {

    const authCtx = useContext(AuthContext);

    return (
        <Stack.Navigator
            screenOptions={{
                headerStyle: {backgroundColor: Colors.primary500},
                headerTintColor: 'white',
                contentStyle: {backgroundColor: Colors.primary100},
            }}
        >
            <Stack.Screen name="Welcome" component={WelcomeScreen} options={{
                // Logout Functionality
                headerRight: ({tintColor}) =>
                    <IconButton icon="exit" color={tintColor} size={24} onPress={authCtx.logout} />
            }}/>
        </Stack.Navigator>
    );
}

function Navigation() {

    const authCtx = useContext(AuthContext);
    return (
        <NavigationContainer>
            {!authCtx.isAuthenticated && <AuthStack/> }
            {authCtx.isAuthenticated && <AuthenticatedStack/> }
        </NavigationContainer>
    );
}

export default function App() {
    return (
        <>
            <StatusBar style="light"/>
            <AuthContextProvider>
                <Navigation/>
            </AuthContextProvider>

        </>
    );
}
