import {Button, FlatList, ScrollView, StyleSheet, Text, TextInput, View} from 'react-native';
import {useState} from "react";

/**
 *  - <ScrollView> is great if we want to add scrolling around some content like article that's too long to fit on a screen,
 *      or we don't know which device sizes our users will be using & we want to make sure that the article is scrollable.
 *          - Good for limited amount of content like article (that has a fixed end at some point)
 *
 *  - But for list (like below), ScrollView is not perfect. Why ?
 *      - List can become very long with 100s or 1000s of items. Now the <ScrollView> always renders all the items/children
 *          that're inside of it whenever the overall UI is rendered no matter if it's visible or not. This can lead to Performance issue.
 *
 *  - Better solution is to use <FlatList> component (inbuilt comp provided by React Native). This is specifically built for scrollable lists.
 *      - Internally, this component only renders the items that're actually visible & other off-screen items will only e loaded
 *          & rendered lazily as they're needed when the user is scrolling.
 *
 *      - Internally, <FlatList> maintains a small threshold to make sure it already starts loading & rending items before they're visible,
 *          but it will only render other items as the user gets close to them while user is scrolling the list.
 *      - We no longer required to map our data manually. Instead, we can pass this task to FlatList so that it can render the list efficiently.
 *          This can be done by using 2 imp. required props of <FlatList> component
 *          1. "data" prop: Points at the data that should be output in the list. For e.g., courseGoals array
 *          2. "renderItem" prop
 *              - This prop wants func as a value that will tell FlatList how to render the individual data items.
 *              - This func receives the "itemData" as param automatically i.e., FlatList will pass this "itemData" to the func & calls whenever
 *                  it determines that a new item must be rendered coz the user is scrolling & a new item should be made visible.
 *              - This func returns the JSX code that should be rendered for the given item.
 *              - This "itemData" is a js object generated by FlatList internally with some values like item (holds the actual data) & metadata.
 *
 *      - When using <FlatList>, there are 2 ways of adding "key" prop to the list items
 *          1. Turn the item/data values from primitive values into objects with a key property.
 *              - E.g., {text: "Goal 1", key: "unique_key"}
 *              - <FlatList> will automatically look for "key" property associated with item.
 *
 *         2. Use FlatList's "keyExtractor" prop
 *              - It's possible that we don't have a property named "key" (in case we're getting from API response) &
 *                  we don't want to transform it just becoz FlatList need the property named "key", we can use "keyExtractor" prop
 *              - "keyExtractor" prop wants a func as value with "item" & "index" as param
 *
 */
export default function App() {

    const [enteredGoalText, setEnterGoalText] = useState('');
    const [courseGoals, setCourseGoals] = useState([]);

    const goalInputHandler = (enteredText) => {
        setEnterGoalText(enteredText);
    };

    const addGoalHandler = () => {
        setCourseGoals(currentCourseGoals =>
            [...currentCourseGoals,
                // {text: enteredGoalText, key: Math.random().toString()}
                {text: enteredGoalText, id: Math.random().toString()}
            ]);
    };

    return (
        <View style={styles.appContainer}>
            <View style={styles.inputContainer}>
                <TextInput style={styles.textInput} placeholder="Your course goal" onChangeText={goalInputHandler} />
                <Button title="Add Goal" onPress={addGoalHandler} />
            </View>
            <View style={styles.goalsContainer}>
                {/*
                <FlatList data={courseGoals} renderItem={(itemData) => {
                    return (
                        <View style={styles.goalItem}>
                            <Text style={styles.goalText}>{itemData.item.text}</Text>
                        </View>
                    );
                }}/>
                */}

                <FlatList data={courseGoals} renderItem={(itemData) => {
                    return (
                        <View style={styles.goalItem}>
                            <Text style={styles.goalText}>{itemData.item.text}</Text>
                        </View>
                    );
                }}
                keyExtractor={(item, index) => {
                    return item.id;
                }}
                />
            </View>
        </View>
    );
}

const styles = StyleSheet.create({
    appContainer: {
        flex: 1,
        paddingTop: 50,
        paddingHorizontal: 16
    },
    inputContainer: {
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 24,
        borderBottomWidth: 1,
        borderBottomColor: '#cccccc',
    },
    textInput: {
        borderWidth: 1,
        borderColor: '#cccccc',
        width: '70%',
        marginRight: 8,
        padding: 8,
    },
    goalsContainer: {
        flex: 5,
    },
    goalItem: {
        margin: 8,
        padding: 8,
        borderRadius: 6,
        backgroundColor: '#5e0acc',
    },
    goalText: {
        color: 'white',
    }
});
